name: tiede_builder_pkg
description: "Package para builder de UI's sem renderização de toda interface, será reconstruído somente widgets que precisam de renderização."
version: 1.0.0
repository: https://github.com/jacsontiede85/tiede_builder_pkg
homepage: https://github.com/jacsontiede85/tiede_builder_pkg

platforms:
  android:
  ios:
  web:
  windows:
  linux:

licenses:
  - "MIT"
  
environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  


flutter:
